theme: jekyll-theme-cayman
exclude: ["README.md"]

title: OrganoidTracker
description: Machine learning driven 3D cell tracking with accurate error predictions
gfrd_title: "OrganoidTracker.org"
gfrd_website: "OrgnaoidTracker.org"

company_name: "AMOLF"
company_website: "https://www.amolf.nl"
group_website: "https://www.amolf.nl/research/biochemical-networks/"

github_repository: "https://github.com/gfrd/modern_egfrd.git"
github_download_zip: "http://github.com/gfrd/modern_egfrd/zipball/master"
github_download_tar: "http://github.com/gfrd/modern_egfrd/tarball/master"
github_install_instructions: "https://github.com/gfrd/modern_egfrd/blob/master/INSTALL.md"
github_issue_tracker: "https://github.com/gfrd/modern_egfrd/issues"
github_old_repository: "https://github.com/gfrd/egfrd.git"

visualstudio_website: "https://www.visualstudio.com"
