theme: jekyll-theme-cayman
exclude: ["README.md"]

markdown: kramdown 

title: OrganoidTracker
description: Machine learning driven 3D cell tracking with accurate error predictions
gfrd_title: "OrganoidTracker.org"
gfrd_website: "OrganoidTracker.org"

company_name: "AMOLF"
company_website: "https://www.amolf.nl"
jeroen_website: "https://amolf.nl/research-groups/quantitative-developmental-biology"
sander_website: "https://sandertanslab.nl"
hugging_face_website: "https://huggingface.co/spaces/sjtans/OrganoidTracker2_pytorch"
paper: "https://www.biorxiv.org/content/10.1101/2024.10.11.617799v1"

github_repository: "https://github.com/gfrd/modern_egfrd.git"
github_download_zip: "http://github.com/gfrd/modern_egfrd/zipball/master"
github_download_tar: "http://github.com/gfrd/modern_egfrd/tarball/master"
github_install_instructions: "https://jvzonlab.github.io/OrganoidTracker/INSTALLATION.html"
github_documentation: "https://jvzonlab.github.io/OrganoidTracker/"
github_issue_tracker: "https://github.com/gfrd/modern_egfrd/issues"
github_old_repository: "https://github.com/gfrd/egfrd.git"

visualstudio_website: "https://www.visualstudio.com"
